version: '3.2'
services:
  editor:
    image: service-maputnik-editor:latest
    build: ./apps/editor
    ports:
      - "8001:8001"
    volumes:
      - ./apps/editor:/code:delegated
    working_dir: /code
    command: npm start -- --host 0.0.0.0 --port 8001
  gatekeeper:
    image: service-maputnik-gatekeeper:latest
    build: 
      context: ./apps/gatekeeper
      dockerfile: ../../config/gatekeeper/Dockerfile
    environment:
      OAUTH_CLIENT_ID: "${GK_OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${GK_OAUTH_CLIENT_SECRET}"
    ports:
      - "9999:9999"
    volumes:
      - ./apps/gatekeeper:/code
    working_dir: /code
    command: sh -c "node index.js"
  haproxy:
    image: service-maputnik-haproxy:latest
    build: 
      dockerfile: Dockerfile
      context: ./config/haproxy
    ports:
      - "8080:8080"
